#!/usr/bin/env bash
# hb-report.sh — render Huntbuddy findings.md into a single self-contained HTML report
# Usage: hb-report.sh <findings.md> [out.html]
set -euo pipefail

SRC="${1:-}"
OUT="${2:-${SRC%.md}.html}"

if [ -z "$SRC" ] || [ ! -f "$SRC" ]; then
  echo "usage: hb-report.sh <findings.md> [out.html]" >&2
  exit 2
fi

python3 - "$SRC" "$OUT" <<'PY'
import sys, html, re, datetime
src, out = sys.argv[1], sys.argv[2]
raw = open(src, encoding="utf-8", errors="replace").read()

# super-minimal markdown-ish rendering (headlines, bold, code blocks, lists)
def esc(t): return html.escape(t)

def render(t):
    lines = t.split("\n")
    html_lines = []
    in_code = False
    for ln in lines:
        if ln.strip().startswith("```"):
            if in_code:
                html_lines.append("</pre>")
                in_code = False
            else:
                html_lines.append("<pre>")
                in_code = True
            continue
        if in_code:
            html_lines.append(esc(ln))
            continue
        s = ln
        s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        if s.startswith("### "):
            html_lines.append(f"<h3>{esc(s[4:])}</h3>")
        elif s.startswith("## "):
            html_lines.append(f"<h2>{esc(s[3:])}</h2>")
        elif s.startswith("# "):
            html_lines.append(f"<h1>{esc(s[2:])}</h1>")
        elif s.strip().startswith(("- ", "* ")):
            html_lines.append(f"<li>{s.strip()[2:]}</li>")
        elif s.strip() == "":
            html_lines.append("")
        else:
            html_lines.append(f"<p>{s}</p>")
    if in_code:
        html_lines.append("</pre>")
    return "\n".join(html_lines)

title = "Huntbuddy Report"
m = re.search(r"#\s+(.+)", raw)
if m: title = esc(m.group(1).strip())

page = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;line-height:1.5;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1c1c1e;background:#fff}}
h1,h2,h3{{line-height:1.2}}
pre{{background:#f4f5f7;padding:0.9rem;border-radius:6px;overflow-x:auto;font-size:0.9em}}
code{{background:#eef0f2;padding:0.1rem 0.3rem;border-radius:4px}}
li{{margin:0.15rem 0}}
small{{color:#777}}
</style></head>
<body>
<small>Generated by Huntbuddy · {datetime.date.today().isoformat()}</small>
{render(raw)}
</body></html>"""
open(out, "w", encoding="utf-8").write(page)
print(f"report written: {out}")
PY